server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

secret:
  test: ${RINSABBIT_SECRET}
