# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "rinsabbit" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: testing yml environment varialble
        env:
          RINSABBIT_SECRET : ${{ secrets.rinsabbit_secret }}
          MORE_SECRET: ${{ secrets.rinsabbit_secret }}
        run: |
          echo github secrets: ${{ secrets.rinsabbit_secret }}
          echo rinsabbit secret: $RINSABBIT_SECRET
          echo more secret: ${RINSABBIT_SECRET}
          echo environment secret: ${{secrets.env_secret}}
          echo environment variable: ${{vars.env_var}}
          
